gems: ['kramdown']
exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor', 'Procfile', 'Rakefile']
page_gen:
  - data: makergrounds
    template: site
    name: slug
    dir: locations
    extension: html
